### ISSUE TITLE
[Question] Does the AppID mean pkgname?

### ISSUE THREAD

**Issue by zuozhen** [ikolomiko/gplay-downloader#5]
When I try to download this app: https://play.google.com/store/apps/details?id=com.pinger.textfree, I got following error:

`getQuery error at AppId com.pinger.textfree AppNotSupported(reason=App not supported)
AppNotSupported(reason=App not supported)
        at com.aurora.gplayapi.helpers.PurchaseHelper.purchase(PurchaseHelper.kt:135)
        at gplay.downloader.Downloader.getQuery(Downloader.kt:30)
        at gplay.downloader.Downloader.downloadAll(Downloader.kt:111)
        at gplay.downloader.AppKt.main(App.kt:113)
NOTFOUND AppId com.pinger.textfree`

Seems the "AppID" is not the pkgname? Where can I find the correct one please?

**Comment by ikolomiko** [comment]
AppId is the string that comes after `details?id=` in the app's Play Store URL. So yeah, you got the correct one. The issue is about either some property of the spoof device gplay-downloader uses, or there is a locale (country + language) restriction on this app. I suppose it's the latter, since I get an error stating that this app is not available in my country.

gplay-downloader uses the default locale settings of the Java runtime it is running on. Have you tried modifying this line and using a different locale? https://github.com/ikolomiko/gplay-downloader/blob/34d63bcdc102dd3f2ad8dec1ed953d5d01685549/app/src/main/kotlin/gplay/downloader/SpoofProvider.kt#L53

**Comment by zuozhen** [comment]
Thanks for your reply.
I replace that line with "return Locale.US" and then build the jar, but still get same error while the package "com.pinger.textfree" is available in US though.

**Comment by ikolomiko** [comment]
Well, in that case, it may be related to the device you used to obtain the AASToken. You can try using another device to obtain a new AASToken, or you can use the Aurora dispenser backend using the `-d` command line flag. Aurora dispenser provides a new gmail account for each 3 apps. However, overusing the Aurora dispenser backend might get you rate-limited for some time, so be aware :)

**Comment by zuozhen** [comment]
OK, thanks. I may try that later.
