### ISSUE TITLE
Does not work (AppNotSupported)

### ISSUE THREAD

**Issue by ArK0Se** [ikolomiko/gplay-downloader#6]
Hello, when I tried the application I got this error, what am I doing wrong?

=====Initialized=====
Initialized config manager
Getting 1/1 AppId com.android.chrome
Getting next downloader config
Logged in as notmymail@gmail.com
getQuery error at AppId com.android.chrome AppNotSupported(reason=App not supported)
AppNotSupported(reason=App not supported)
        at com.aurora.gplayapi.helpers.PurchaseHelper.purchase(PurchaseHelper.kt:135)
        at gplay.downloader.Downloader.getQuery(Downloader.kt:30)
        at gplay.downloader.Downloader.downloadAll(Downloader.kt:111)
        at gplay.downloader.AppKt.main(App.kt:113)
NOTFOUND AppId com.android.chrome
=====Finished=====

**Comment by ikolomiko** [comment]
Hello, apologies for the late reply. I was busy getting destroyed by my midterm exams :P

The error is probably related to the default spoof device, which supports a relatively old Android SDK level. Since `gplay-downloader` doesn't provide an easy way to change the spoof device as of now, you can try a workaround like this:
1. Delete all files in `app/src/main/resources/device-props/` except `sm_s9_plus.properties` .
2. Rebuild the program and run it as usual.
3. ???
4. Profit.

Let me know if it helps!

**Comment by ikolomiko** [comment]
Closing the issue due to inactivity.
